matrix:
  include:
  - env: Ubuntu=14.04
    os: linux
    dist: trusty
    sudo: required
before_install:
- "./.ci/before_install.sh"
install:
- "./.ci/install.sh"
script:
- "./.ci/script.sh"
git:
  depth: 3
notifications:
  slack:
    secure: YeX0nhy+E/TlWwKGEFfbzHPevHkn0xQX+lQw38QjMdlhdkWlV5rJ+alD0Cc/embvyCkVkFS8qFIHlS3gT0DdQXQpTXd3oyX61Qx6KHypjeABp6mfAAhujz0LoInNOWmPja4HkuocqGl0sktQ3x9BI2H3bf179SEU5VP3s9Dwan63afCfni6AXvRUcGPQebihlnQ9/tTv9e1Pw3awAiWkhAlz5BytnmScBKsmtBFSBcSXneYV7ixMnDa+IMJu7dpfzNUtfT2MwrFtqgKQchluVnYBXeKkqQFhPsoJzudvRX9ETWPGhTUbXYAu4fPWV0EnL2GTNAjD7RfjtJ7PvtWLLPURS/ustRETUkIphUsf5DPCp7QYF8AWqANz6rxbvgWNDGNQrXcSARHh2clYyGyD8pzzzxPdeP3LwoyUsgsa/JCg20qywcYhDplZRyKJoHJR+Yl88+8T4uLPdXUW/GJbFcqjQc+cYCXwtYt4lpmafB2LzZczenH4jSlRuxxuYvvNMx0k8+hvz70p0d2Psl+mrVjGAdCUYgPUZP5GNmkZXPCsw8ZzpfQDaG78noAm9mcyjJPfRsnqj+AyNytxl+ZsUwqICmoOog8qVNMLMGgtBE5apXzqzP/O0P8IqJd06PNzPR8N100KMPLks57LE0WOJGFbzLPS4FcznGaxFPLiluY=
