matrix:
  include:
  - env: Ubuntu=14.04
    os: linux
    dist: trusty
    sudo: required
before_install:
- "./.ci/before_install.sh"
install:
- "./.ci/install.sh"
script:
- "./.ci/script.sh"
git:
  depth: 3
notifications:
  slack:
    secure: VnR39QE7jGnM0QoPThx3xnEz8msyxTiQemuHf1st/iqt0/jOqBJXGrDlVD80KeoxbaIvpH2+vaTOWi2Ul4sS5hTUstBe45Zop4TGcRQRUH8OYcdoTQ5yPXczF0oxMpV4eWbBMXLX46l1EqpMO63P0gKo4ilFZG3qSEH1FTGj51+BmMuoG2OXEWygm3+9cApZAOfZxEubkbfL9RuKfPJX+UeUB0pQ6s+00kmwVAQvIZclfHqy5ttHjoxNF+cj4rTaV5PZcU/1/YcUj2POgtRedfBzHcJhXIxj4Fp/Mq+OLcKW70Rl+Hd9aYvM+7EnSOnxZU5i/+HWRLZLUAjQ2+nciL1yIkpOKR9yDQqu3lGeEINaHhZ2q7z5AL0+c8qv0PF9p51C4k4DoVEKzMGK6F5eux6QCk2vAxiD7oWbNAsZcw1bv5pNVEOD8qUW432+/gFoKL/MjeYvfJUn9Fp1Iqdd1divor22lL6difzUyc/Vh4EWA56vhFTVK2yNH9pcAEWZIrYxTffVp7jR8xQPZblENQ1ljDhzQXLGCp72xI3IaK4y169pa40ePz+MPQjc9drY3sJbplMcCfuRKwP4g6Z+UZ0QK18YXPhL/pcz+fsktZSRmql5LR/RetP4/aEqAZg/EbKfK6upD07mOY5ubaOLvD40JNiU2fkyWCmjK1xQKog=
