matrix:
  include:
  - env: Ubuntu=14.04
    os: linux
    dist: trusty
    sudo: required
before_install:
- "./.ci/before_install.sh"
install:
- "./.ci/install.sh"
script:
- "./.ci/script.sh"
git:
  depth: 3
notifications:
  slack: everestexpedition:TpfqnAdynSMihaJ5XJRRV66x